# Generated by Django 2.2.1 on 2019-05-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjworld', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mjworld',
            old_name='kind',
            new_name='menu',
        ),
        migrations.RemoveField(
            model_name='mjworld',
            name='address',
        ),
        migrations.AddField(
            model_name='mjworld',
            name='takeout',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mjworld',
            name='time',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
