# Generated by Django 2.2.1 on 2019-05-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('time', models.CharField(blank=True, max_length=40)),
                ('subtitle1', models.CharField(blank=True, max_length=40)),
                ('content1', models.TextField(blank=True)),
                ('subtitle2', models.CharField(blank=True, max_length=40)),
                ('content2', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=40)),
                ('hyperlink', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('time', models.CharField(blank=True, max_length=40)),
                ('subtitle1', models.CharField(blank=True, max_length=40)),
                ('content1', models.TextField(blank=True)),
                ('subtitle2', models.CharField(blank=True, max_length=40)),
                ('content2', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=40)),
                ('hyperlink', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
