# Generated by Django 2.2.1 on 2019-05-12 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lost_property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lost',
            name='password',
        ),
        migrations.AlterField(
            model_name='lost',
            name='author',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
