# Generated by Django 2.2.1 on 2019-05-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
