# Generated by Django 2.2.1 on 2019-05-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_property', '0002_auto_20190510_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
