# Generated by Django 2.2.1 on 2019-05-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_property', '0005_auto_20190510_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
