# Generated by Django 2.2.1 on 2019-05-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost_property', '0007_auto_20190512_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lost',
            name='author',
        ),
    ]
