# Generated by Django 2.2.1 on 2019-05-10 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lost_property', '0006_auto_20190510_2225'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lost_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='publish')),
                ('author', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_comment', to='lost_property.Lost')),
            ],
        ),
        migrations.CreateModel(
            name='Board_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='publish')),
                ('author', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_comment', to='board.Board')),
            ],
        ),
    ]
