# Generated by Django 2.2.1 on 2019-05-10 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        ('lost_property', '0006_auto_20190510_2225'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='publish')),
                ('author', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='publish')),
                ('author', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lost_property.Lost')),
            ],
        ),
        migrations.RemoveField(
            model_name='lost_comment',
            name='title',
        ),
        migrations.DeleteModel(
            name='Board_comment',
        ),
        migrations.DeleteModel(
            name='Lost_comment',
        ),
    ]
