# Generated by Django 2.0.6 on 2019-05-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20190511_1902'),
        ('comment', '0003_auto_20190511_1852'),
    ]

    operations = [
    ]
