# Generated by Django 2.2.1 on 2019-05-13 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='publish')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('content', models.TextField()),
                ('purpose', models.CharField(choices=[('속보', '[속보]'), ('택시', '[택시]'), ('합석', '[합석]'), ('기타', '[기타]')], default='기타', max_length=10)),
                ('author', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
