# Generated by Django 2.2.1 on 2019-05-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='publish')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('content', models.TextField()),
                ('password', models.CharField(max_length=20)),
                ('purpose', models.CharField(choices=[('속보', '[속보]'), ('택시', '[택시]'), ('합석', '[합석]'), ('기타', '[기타]')], default='기타', max_length=10)),
            ],
        ),
    ]
