# Generated by Django 2.0.6 on 2019-05-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20190512_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='purpose',
            field=models.CharField(choices=[('택시', '[택시]'), ('긴급', '[긴급]'), ('자유', '[자유]')], default='자유', max_length=10),
        ),
    ]
